# Generated by Django 3.2.4 on 2021-10-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Un utilisateur avec cet email existe déjà.'}, max_length=254, unique=True),
        ),
    ]
